name: FGM
description: The Force of Grace Ministry
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  hive: ^2.2.3
  flutter_svg: ^1.1.6
  http: ^0.13.5
  smooth_page_indicator: ^1.0.1
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.32
  just_audio_background: ^0.0.1-beta.9
  rxdart: ^0.27.7
  get: ^4.6.5
  http_interceptor: ^1.0.2
  shimmer: ^2.0.0
  flutter_file_downloader: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: images/app-logo.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: images/app-logo.png
    background_color: '#FFFFFF'
    theme_color: '#007AFF'
  windows:
    generate: true
    image_path: images/app-logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: images/app-logo.png
flutter_native_splash:
  color: '#FFFFFF'
  color_dark: '#FFFFFF'
  android_12:
    icon_background_color: '#FFFFFF'
    icon_background_color_dark: '#FFFFFF'
flutter:
  uses-material-design: true
  assets:
  - images/
  - audio/
